[profile.default]
src = "impl"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
gas_reports = ["Heed"]
fuzz = { runs = 4096 }
invariant = { runs = 256, depth = 64, fail_on_revert = false }

[profile.layer2]
evm_version = "shanghai"

[rpc_endpoints]
taiko-mainnet = "https://rpc.mainnet.taiko.xyz"
taiko-hoodi = "https://rpc.hoodi.taiko.xyz"
anvil = "http://127.0.0.1:8545"

[etherscan]
taiko-mainnet = { key = "${TAIKOSCAN_API_KEY}", url = "https://api.taikoscan.io/api", chain = 167000 }
taiko-hoodi = { key = "${TAIKOSCAN_API_KEY}", url = "https://api-hoodi.taikoscan.io/api", chain = 167013 }
